### ISSUE TITLE
Login workflow ne funkcionira

### ISSUE THREAD

**Issue by brunoAltinet** [altibiz/mess#36]
### Problem

Otvaranje aplikacije ne funkcionira bez logina. 

### Željeno ponašanje

Potrebno je da postoji konkretan flow za login bez da se rucno upisuje /login i slicno. Aplikacija mora stalno biti funkcionalna i user friendly.

### Koraci za reprodukciju

Otvoriti aplikaciju.Dobije se prazan ekran

**Comment by GabrijelAB** [comment]
Flow napravljen, zasada se sve vrti oko login stranice. 
U Blazor dijelu se u sidebar-u vide samo stranice koje pojedini user smije gledat.
Orcherd dio se nije dirao, samo je stavljena redirekcija na login kada se dođe na base url stranice.
